### ISSUE TITLE
Find good Date Picker for input-date

### ISSUE THREAD

**Issue by zmon** [codeforkansascity/cmr-clinic#1]
in `components/input-date.vue` there is a standard text input.
We tried HTML 5 type `date`, but it did not work on all browsers.

Preferably it would save the date in a format that MySQL date type would except.

Currently `input-date` is being used in the `section-persons-information.vue` Date of birth and Expiration date.  

It also needs to be added to `input-conviction-fields.vue` Release Date

**Comment by mattsplat** [comment]
#8
